[package]
name = "simulation-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.6"
rand = "0.8"
uuid = "1.3"
clap = { version = "3.1", features = ["derive"] }
log = "0.4"
bevy_prototype_debug_lines = "0.6"